name: 'angular_dart_demo'
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: "1.1.0"
  web_components: "0.10.1"
  browser: ">=0.10.0+2 <0.11.0"
  dartson: "0.2.3"
  sass: "0.4.2"
  bootjack: "0.6.5"
transformers:
- dartson
- sass
- angular
